import { boolean, integer, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }) })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })

export const products = pgTable('products', { id: serial('id').primaryKey(), userId: text('userId').notNull(), name: text('name').notNull(), slug: text('slug').notNull(), category: text('category').notNull(), description: text('description').notNull(), price: integer('price').notNull(), compareAtPrice: integer('compareAtPrice'), image: text('image').notNull(), stock: integer('stock').notNull().default(0), status: text('status').notNull().default('draft'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const orders = pgTable('orders', { id: serial('id').primaryKey(), userId: text('userId').notNull(), customerName: text('customerName').notNull(), customerEmail: text('customerEmail').notNull(), total: integer('total').notNull(), status: text('status').notNull().default('pending'), createdAt: timestamp('createdAt').notNull().defaultNow(), fulfilledAt: timestamp('fulfilledAt') })
export const pageVisits = pgTable('page_visits', { id: serial('id').primaryKey(), userId: text('userId'), path: text('path').notNull(), visitorKey: text('visitorKey'), createdAt: timestamp('createdAt').notNull().defaultNow() })
